# Generated by Django 5.2.15 on 2026-07-06 09:34

import apps.cms.models.contact_request
import apps.cms.models.hero_banner
import apps.cms.models.news
import apps.cms.models.partner
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cms_about_us',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_number', models.CharField(db_index=True, default=apps.cms.models.contact_request.generate_ticket_number, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('subject', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to=apps.cms.models.contact_request.contact_request_upload_to)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], db_index=True, default='MEDIUM', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cms_contact_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cms_faq',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, default='', max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.cms.models.hero_banner.hero_banner_upload_to)),
                ('video_url', models.URLField(blank=True, max_length=500, null=True)),
                ('button_text', models.CharField(blank=True, max_length=100, null=True)),
                ('button_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cms_hero_banner',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('summary', models.TextField(blank=True, default='')),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.cms.models.news.news_upload_to)),
                ('video_url', models.URLField(blank=True, max_length=500, null=True)),
                ('button_text', models.CharField(blank=True, max_length=100, null=True)),
                ('button_url', models.URLField(blank=True, max_length=500, null=True)),
                ('type', models.CharField(choices=[('NEWS', 'News'), ('ANNOUNCEMENT', 'Announcement')], db_index=True, default='NEWS', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cms_news_article',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.ImageField(upload_to=apps.cms.models.partner.partner_upload_to)),
                ('website_url', models.URLField(blank=True, max_length=500, null=True)),
                ('type', models.CharField(choices=[('SPONSOR', 'Sponsor'), ('PARTNER', 'Partner')], db_index=True, default='PARTNER', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cms_partner',
                'ordering': ['title'],
            },
        ),
    ]
