"""Abstract base class for payment providers.

Defines the contract that every concrete payment provider must implement.
The ``PaymentService`` dispatches to the active provider through this
interface, keeping business modules decoupled from provider specifics.
"""

from abc import ABC, abstractmethod


class BasePaymentProvider(ABC):
    """Abstract payment provider interface.

    Concrete subclasses must implement ``initialize()`` and ``verify()``
    for their respective payment gateway.
    """

    @abstractmethod
    def initialize(
        self,
        amount: float,
        currency: str,
        reference: str,
        callback_url: str,
        customer: dict,
    ) -> dict:
        """Initialize a payment transaction with the provider.

        Args:
            amount: Payment amount in the smallest currency unit or
                decimal, depending on the provider.
            currency: ISO 4217 currency code (e.g. ``"ETB"``, ``"USD"``).
            reference: Unique transaction reference generated by the
                calling business service.
            callback_url: URL for the provider to notify on completion.
            customer: Dictionary with at least ``email`` and optionally
                ``first_name``, ``last_name``, ``phone_number``.

        Returns:
            Normalized dict with keys: ``status``, ``reference``,
            ``amount``, ``currency``, ``checkout_url``, ``raw``.

        Raises:
            PaymentProviderError: On initialisation failure.
        """

    @abstractmethod
    def verify(self, reference: str) -> dict:
        """Verify a payment transaction by reference.

        Args:
            reference: The transaction reference to verify.

        Returns:
            Normalized dict with keys: ``status``, ``reference``,
            ``amount``, ``currency``, ``raw``.

        Raises:
            PaymentProviderError: On verification failure.
        """
