# Generated by Django 5.2.15 on 2026-07-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userassignment',
            index=models.Index(fields=['is_active'], name='accounts_us_is_acti_3619d2_idx'),
        ),
    ]
