# Generated by Django 5.2.15 on 2026-07-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_loginattempt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Suspended', 'Suspended'), ('Archived', 'Archived')], db_index=True, default='Pending', max_length=20),
        ),
    ]
