# Generated by Django 5.2.15 on 2026-07-04 21:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_add_userassignment_is_active_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('resource_type', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('resource_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='accounts.branch')),
            ],
            options={
                'db_table': 'shared_audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='audit_created_idx'), models.Index(fields=['action'], name='audit_action_idx'), models.Index(fields=['resource_type'], name='audit_res_type_idx'), models.Index(fields=['resource_id'], name='audit_res_id_idx')],
            },
        ),
    ]
